### ISSUE TITLE
Controller Not Recognized In Game

### ISSUE THREAD

**Issue by mholubinka1** [SirMangler/dolphin#14]
Dolphin UWP recognizes the controller automatically on start, but opening any game means the inputs no longer register (except for the Xbox Home button).

The Dolphin quick menu can't be opened and the game can't be played.

This also happens with controller profiles so it isn't a configuration issue.

**Comment by qwerty9537** [comment]
same issue here, hope it gets resolved soon. i have an animal crossing save on there :P

this also happens on 1.1.5.2 for me, I'm not sure why this bug began

**Comment by qwerty9537** [comment]
Solution found! 

Matt, your xbox is in English (UK) right? It needs to be set to English (USA) for some reason.

**Comment by mholubinka1** [comment]
That fixed it!

Change you language and location to English (US)

**Comment by mediaexplorer74** [comment]
> your xbox is in English (UK) right? It needs to be set to English (USA) for some reason.

Wow, first sactions against Great Britain. Cool
